---

- name: Install docker
  include: "install-{{ ansible_os_family|lower }}.yml"

- meta: flush_handlers

- name: Enable and start docker
  service:
    name: docker
    enabled: yes
    state: started

- name: Create logrotate config for docker container logs
  template:
    src:   docker-container.logrotate.j2
    dest:  /etc/logrotate.d/docker-container-logs
    mode:  0644
  when: docker_container_logs_rotate

- name: Install docker cleanup script
  include: "cron.yml"
